name: Build Daily News (Python)
on:
  schedule:
    - cron: "0 0 * * *"   # 05:30 IST daily (00:00 UTC). Change to '0 * * * *' for hourly.
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch & build JSON
        run: python scripts/fetch_feeds.py
      - name: Commit JSON changes
        run: |
          git config user.name "news-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git commit -m "auto: update news JSON" || echo "No changes to commit"
          git push
